#use postgresqul in production
#
development:
  adapter: postgresql
  encoding: unicode
  database: gypzvibes-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gypzvibes-test
  pool: 5
  port: 5432
  host: localhost