development:
  adapter: postgresql
  encoding: unicode
  database: gypzvibes_development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gypzvibes_test
  pool: 5
  port: 5432
  host: localhost